# Generated by Django 3.2.4 on 2021-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_image_title',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_video_title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
