# Generated by Django 3.2.4 on 2021-07-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_course_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_evaluation', models.TextField()),
                ('evaluation_rating', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.course')),
            ],
        ),
    ]
