# Generated by Django 3.2.4 on 2021-07-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='courses/')),
                ('description', models.TextField(max_length=2500, null=True)),
                ('summary', models.TextField(max_length=140, null=True)),
                ('rating', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('author', models.CharField(max_length=100)),
                ('link', models.URLField(default='#')),
                ('discount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.category')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_evaluation', models.TextField()),
                ('evaluation_rating', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='affiliate.course')),
            ],
            options={
                'ordering': ('-evaluation_rating',),
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image_title', models.CharField(max_length=50)),
                ('ad_image', models.ImageField(upload_to='ad/img/%Y/%m/%d/')),
                ('ad_video_title', models.CharField(max_length=50)),
                ('ad_video', models.FileField(upload_to='ad/video/%Y/%m/%d/')),
                ('ad_text', models.TextField(max_length=2500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='affiliate.course')),
            ],
        ),
    ]
