# Generated by Django 3.2.4 on 2021-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pain_point',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
